### ISSUE TITLE
Migrate to Polymer 2

### ISSUE THREAD

**Issue by alshakero** [Starcounter/CssVariablesManager#41]

**Comment by alshakero** [comment]
This is waiting for https://github.com/Juicy/juicy-color-picker/pull/7 since it depends on it.

**Comment by alshakero** [comment]
I finished Juicy/juicy-color-picker#7 and waiting for https://github.com/Juicy/juicy-popover/pull/16 now.

**Comment by warpech** [comment]
Please note that this issue has to be split into two PRs:

- PR that changes the views to be hybrid, targeted at `master`
- PR that adds CEv1 version of `juicy-color-picker` and `juicy-popover`, targeted at `master-2.4` (depends on https://github.com/Juicy/juicy-popover/pull/16 and https://github.com/Starcounter/CssVariablesManager/issues/42)

**Comment by PatrykSzwer** [comment]
Views are translated to hybrid, elements were updated to CEv1 and `master` was merged to `master-2.4` branch. Closing this issue as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/CssVariablesManager/releases/tag/1.0.0
- published in the App Warehouse
