### ISSUE TITLE
Release the final version of this app

### ISSUE THREAD

**Issue by warpech** [Starcounter/CssVariablesManager#47]
@PatrykSzwer can you please release the final version of this app?

**Comment by PatrykSzwer** [comment]
I want to wait with the final release until https://github.com/Starcounter/Blending/pull/48#issuecomment-357916686 will be confirmed because right now I'm not sure if the app works correctly. If not, We will have to do some fixing before release.

**Comment by PatrykSzwer** [comment]
Since https://github.com/Starcounter/Blending/pull/48#issuecomment-357916686 was confirmed as not a bug in this app, I've released CssVariablesManager in version 1.0.0 on github and in the warehouse.
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/CssVariablesManager/releases/tag/1.0.0
- published in the App Warehouse
